### ISSUE TITLE
Season 4 launch checklist

### ISSUE THREAD

**Issue by Blaylock1988** [GV-Kharak/GVK-Settings#187]
- [x] merge S4 branches into main and republish
- [x] Reset Voxels
- [x] Clear safezones (N1Ran shitty plugin)
- [x] Respawn all static encounters
- [x] Clear known steam IDs
- [x] Purge players in SE
- [x] Purge NPC factions
- [x] Delete Grid Backups
- [x] Delete Hangar
- [x] Delete mod content
- [x] Clear server logs
- [x] Clear clear mod content logs
- [x] Back up start save
- [x] Enable SEDB Plugin
